version: '3.8'

services:
  # Test service for automated testing
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: parr-4-the-course-test
    environment:
      - NODE_ENV=test
      - CI=true
      - VITE_SUPABASE_URL=http://supabase-local:54321
      - VITE_SUPABASE_ANON_KEY=${ANON_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24ifQ.625_WdcF3KHqz5amU0x2X5WWHP-OEs_4qj0ssLNHzTs}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - supabase-local
    command: >
      sh -c "npm test -- --coverage --watchAll=false"

  # Supabase local instance for testing
  supabase-local:
    image: supabase/supabase-local
    container_name: supabase-local-test
    ports:
      - "54321:54321"
      - "54322:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      JWT_SECRET: ${JWT_SECRET:-super-secret-jwt-token-with-at-least-32-characters}
      ANON_KEY: ${ANON_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24ifQ.625_WdcF3KHqz5amU0x2X5WWHP-OEs_4qj0ssLNHzTs}
      SERVICE_ROLE_KEY: ${SERVICE_ROLE_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSJ9.vI9obAHOGyVVKa3pD--kJlyxp-Z2zV9UUMAhKpNLAcU}
    volumes:
      - supabase-test-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  supabase-test-data:
    name: parr-4-the-course-supabase-test-data 