version: '3.8'

# Define shared environment variables with hosted Supabase
x-environment: &default-environment
  VITE_SUPABASE_URL: https://fkbmarrbkyshruzwyytn.supabase.co
  VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrYm1hcnJia3lzaHJ1end5eXRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNTk2ODQsImV4cCI6MjA1NzgzNTY4NH0.gTPBLkYHliyAhlsSZtulf8ud0f1lNx4-dTbxflA_b4U

services:
  # Development service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: parr-4-the-course-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      <<: *default-environment
      NODE_ENV: development
    profiles:
      - development

  # Production service
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        - NODE_ENV=production
    container_name: parr-4-the-course-prod
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      <<: *default-environment
      NODE_ENV: production
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    profiles:
      - production

  # Test service
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: parr-4-the-course-test
    environment:
      <<: *default-environment
      NODE_ENV: test
      CI: "true"
    command: >
      sh -c "npm test -- --coverage --watchAll=false"
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - testing

volumes:
  supabase-data:
    name: parr-4-the-course-supabase-data 