
-- Insert initial categories
INSERT INTO categories (name) VALUES
  ('Breakfast'),
  ('Lunch'),
  ('Dinner'),
  ('Dessert'),
  ('Snack'),
  ('Vegetarian'),
  ('Vegan'),
  ('Gluten-Free'),
  ('Low-Carb'),
  ('Quick & Easy'),
  ('Italian'),
  ('Mexican'),
  ('Asian'),
  ('Mediterranean'),
  ('Baking'),
  ('Grilling'),
  ('Soup'),
  ('Salad'),
  ('Pasta'),
  ('Seafood');

-- Insert common ingredients (you can expand this list as needed)
INSERT INTO ingredients (name) VALUES
  ('Salt'),
  ('Pepper'),
  ('Olive Oil'),
  ('Garlic'),
  ('Onion'),
  ('Flour'),
  ('Sugar'),
  ('Eggs'),
  ('Milk'),
  ('Butter'),
  ('Chicken Breast'),
  ('Ground Beef'),
  ('Rice'),
  ('Pasta'),
  ('Tomatoes'),
  ('Bell Peppers'),
  ('Carrots'),
  ('Celery'),
  ('Lemon'),
  ('Cheese');
